# Generated by Django 5.1.5 on 2025-02-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_customuser_delete_habit'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uemail', models.EmailField(max_length=254)),
                ('upassword', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'mydatabase',
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
