# Generated by Django 5.1.5 on 2025-02-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_rename_habit_name_ab_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ab',
            old_name='name',
            new_name='habit_name',
        ),
        migrations.AlterField(
            model_name='ab',
            name='frequency',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ab',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ab',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
