# Generated by Django 5.1.5 on 2025-02-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0006_rename_name_ab_habit_name_alter_ab_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ab',
            name='frequency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ab',
            name='habit_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ab',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
